services:
  orderservice:
    build: ./OrderService
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_URLS: "http://*:8080"

  paymentservice:
    build: ./PaymentService
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_URLS: "http://*:8080"

  apigateway:
    build: ./ApiGateway
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: "http://*:8080"
    depends_on:
      - orderservice
      - paymentservice
